### ISSUE TITLE
요구분석 정의

### ISSUE THREAD

**Issue by ChoiSoonHyeon** [kjw8797/skybluebear#1]
@kjw8797 구글 드라이브 폴더 01. 요구분석 정의 > 요구분석 스프레드 시트를 작성해주시기 바랍니다.

**Comment by kjw8797** [comment]
> 구글 드라이브 폴더 01. 요구분석 정의 > 요구분석 스프레드 시트를 작성해주시기 바랍니다.

@ChoiSoonHyeon 위 사항 완료했습니다. 검토 바랍니다.

**Comment by kjw8797** [comment]
> 구글 드라이브 폴더 01. 요구분석 정의 > 요구분석 스프레드 시트를 작성해주시기 바랍니다.

@ChoiSoonHyeon 작성 완료했습니다. 검토 부탁드립니다.

**Comment by ChoiSoonHyeon** [comment]
> 작성 완료했습니다. 검토 부탁드립니다.

변경전 : 회원가입 
변경 후 : 회원, 가입

@kjw8797 최대한 단어를 분리하여 다시 작성해주시기 바랍니다.

**Comment by ChoiSoonHyeon** [comment]
@kjw8797 

- 요구분석의 1row는 세부 기능사항이 아니라 기능을 전체 포함하는 단위로 작성해주세요.
예) 달력 선택, 일정 등록 X > 일정 관리 O

- ID는 어떠한 의미가 부여된 공통된 규칙으로 이루어져야합니다.
예) F1-20160128 (2016년 1월 28일에 작성된 기능(function, F) 1번째)

- 유형은 기능, 설계, 장비 등의 전체적인 카테고리를 작성해야합니다.

- 내용에 ~를 위해 필요를 제거해주시기 바랍니다.
예) 변경전 : 앱 또는 웹에서 달력의 해당 월을 보기 위해 필요
변경후 : 앱 또는 웹에서 달력의 월을 선택함

**Comment by ChoiSoonHyeon** [comment]
@kjw8797 #2 의 코멘트 내용 의거, 회원 계정에 대한 정보는 불필요합니다.

**Comment by kjw8797** [comment]
> 요구분석의 1row는 세부 기능사항이 아니라 기능을 전체 포함하는 단위로 작성해주세요.
예) 달력 선택, 일정 등록 X > 일정 관리 O

 세부 기능사항을 전체를 포함하는 단위로 변경했습니다.

> ID는 어떠한 의미가 부여된 공통된 규칙으로 이루어져야합니다.
예) F1-20160128 (2016년 1월 28일에 작성된 기능(function, F) 1번째)

ID에 공통된 규칙으로 의미부여 했습니다. 
변경전 : 회원가입
변경후 : F1-160128

> 유형은 기능, 설계, 장비 등의 전체적인 카테고리를 작성해야합니다.

유형 카테고리 형식으로 변경했습니다.

> 내용에 ~를 위해 필요를 제거해주시기 바랍니다.
예) 변경전 : 앱 또는 웹에서 달력의 해당 월을 보기 위해 필요
변경후 : 앱 또는 웹에서 달력의 월을 선택함

'~를 위해 필요'제거 및 기능에 맞는 내용으로 수정 완료했습니다.

@ChoiSoonHyeon 작성 완료했습니다 검토 바랍니다.

**Comment by ChoiSoonHyeon** [comment]
> 작성 완료했습니다 검토 바랍니다.

검토 완료했습니다. close하겠습니다.
